<!DOCTYPE html>
<html lang="pl" dir="ltr">
<head>
    <title>Ants</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://static.ants.vanisoft.pl/css/animate.css" rel="stylesheet">
    <link href="http://static.ants.vanisoft.pl/css/introjs.css" rel="stylesheet">
    <link href="http://static.ants.vanisoft.pl/css/main.css" rel="stylesheet">
    <link type="text/plain" rel="author" href="/humans.txt" />
    <meta name=description content="Write bots">
</head>
<body>
<div id=app></div>
